FROM node:alpine
WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .
CMD [ "npm", "run","start" ]

# create volumes with command line 
#  docker container run -p 3000:3000 -v /app/node_modules -v $(pwd):/app c380192f5492